version: '2'
services:
    front:
        build: .
        container_name: reddit-saver
        volumes:
            - .:/var/www/html/
            - ./php-ini:/usr/local/etc/php/custom.d
        environment:
            PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
            XDEBUG_CONFIG: remote_host=192.168.1.107
        networks:
            - web
        labels:
          - traefik.enable=true
          - traefik.http.routers.reddit-saver.entrypoints=websecure
          - traefik.http.routers.reddit-saver.rule=Host(`ress.itgg.fi`)
          - traefik.http.routers.reddit-saver.middlewares=authelia
networks:
    default:
    web:
        external:
            name: web

